modLoader="javafml"
loaderVersion="[36,)"
license="Academic Free License v3.0"

[[mods]]
modId="meeep_mod"
version="0.0.1"
displayName="Meeep Mod"
credits="Camden"
displayURL="https://meeep.tk"
authors="Camden"

[[dependencies.meeep_mod]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.5]"
    ordering="NONE"
    side="BOTH"




